std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace
exclude_files = { "Includes/", ".claude/" } -- vendored or session-local, never linted

-- The WoW API surface this add-on reads and never writes.
read_globals = {
	"Ambiguate",
	"bit",
	"C_AddOns",
	"C_ChatInfo",
	"C_EventUtils",
	"C_Item",
	"C_QuestLog",
	"C_Seasons",
	"C_Secrets",
	"C_Spell",
	"C_SpellBook",
	"C_Timer",
	"C_TooltipInfo",
	"C_UnitAuras",
	"COMBATLOG_OBJECT_AFFILIATION_MINE",
	"COMBATLOG_OBJECT_AFFILIATION_OUTSIDER",
	"COMBATLOG_OBJECT_AFFILIATION_PARTY",
	"COMBATLOG_OBJECT_AFFILIATION_RAID",
	"COMBATLOG_OBJECT_REACTION_FRIENDLY",
	"COMBATLOG_OBJECT_TYPE_PLAYER",
	"CombatLogGetCurrentEventInfo",
	"CreateFrame",
	"CreateMacro",
	"D_HOURS",
	"D_MINUTES",
	"D_SECONDS",
	"DeleteMacro",
	"Enum",
	"GameTooltip",
	"GetBuildInfo",
	"GetCVar",
	"GetItemStats",
	"GetLocale",
	"GetMacroIndexByName",
	"GetNumMacros",
	"GetPlayerInfoByGUID",
	"GetTime",
	"GetUnitName",
	"InCombatLockdown",
	"IsInGroup",
	"IsInRaid",
	"IsPlayerSpell",
	"issecretvalue",
	"LibStub",
	"LOCALIZED_CLASS_NAMES_MALE",
	"MAXEMOTEINDEX",
	"PlaySoundFile",
	"SetCVar",
	"Settings",
	"TextEmoteSpeechList",
	"UnitClass",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitInParty",
	"UnitInRaid",
	"UnitInRange",
	"UnitIsFriend",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitIsVisible",
	"UnitLevel",
	"UnitName",
	"UnitNameFromGUID",
	"wipe",
	"WorldFrame",
}

-- The closed set of globals this add-on owns: its SavedVariables table and its
-- slash registrations.
globals = {
	"TFTBDB",
	"SLASH_TFTB1",
	-- A field, so only the add-on's own slash entries are writable.
	SlashCmdList = {
		fields = { "TFTB", "TFTB_THANKYOU1", "TFTB_THANKYOU2", "TFTB_THANKYOU3", "TFTB_THANKYOU4", "TFTB_THANKYOU5" },
	},
}
