std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace
exclude_files = { "Includes/" } -- vendored, never linted

-- The WoW API surface this add-on reads and never writes.
read_globals = {
	"Ambiguate",
	"COMBATLOG_OBJECT_AFFILIATION_MINE",
	"COMBATLOG_OBJECT_AFFILIATION_OUTSIDER",
	"COMBATLOG_OBJECT_AFFILIATION_PARTY",
	"COMBATLOG_OBJECT_AFFILIATION_RAID",
	"COMBATLOG_OBJECT_REACTION_FRIENDLY",
	"COMBATLOG_OBJECT_TYPE_PLAYER",
	"C_AddOns",
	"C_CVar",
	"C_EventUtils",
	"C_Item",
	"C_Spell",
	"C_Timer",
	"C_UnitAuras",
	"CombatLogGetCurrentEventInfo",
	"CreateFrame",
	"CreateMacro",
	"D_HOURS",
	"D_MINUTES",
	"D_SECONDS",
	"DeleteMacro",
	"DoEmote",
	"GetAddOnInfo",
	"GetAddOnMetadata",
	"GetBuildInfo",
	"GetCVar",
	"GetItemIcon",
	"GetItemInfo",
	"GetLocale",
	"GetMacroIndexByName",
	"GetNumAddOns",
	"GetNumMacros",
	"GetPlayerInfoByGUID",
	"GetSpellDescription",
	"GetSpellInfo",
	"GetSpellLink",
	"GetSpellTexture",
	"GetTime",
	"GetUnitName",
	"InCombatLockdown",
	"IsAddOnLoaded",
	"IsInGroup",
	"IsInRaid",
	"IsPlayerSpell",
	"LOCALIZED_CLASS_NAMES_MALE",
	"LibStub",
	"MAXEMOTEINDEX",
	"PlaySoundFile",
	"SendChatMessage",
	"SetCVar",
	"Settings",
	"TextEmoteSpeechList",
	"UnitClass",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitInParty",
	"UnitInRaid",
	"UnitInRange",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitIsVisible",
	"UnitLevel",
	"UnitName",
	"WOW_PROJECT_ID",
	"bit",
	"wipe",
}

-- The closed set of globals this add-on owns: its SavedVariables table and its
-- slash registrations.
globals = {
	"TFTBDB",
	"SLASH_TFTB_CONFIG1",
	"SlashCmdList",
}
